#!/bin/bash
# change input dataset in array "dataset" and path "DATA..."
# change tesing count in var "seqcount"
# change number of iterations in "simtime"
# change number of thrs in array "thrsset_MC" "thrsset_D6" "thrsset_N8"
# store timing data in "RESULT"


# ----- dataset loop begin -----

#dataset=(10240 20480 40960 81920 163840 327680)
dataset=(16 32 64 128 256)
  for size in ${dataset[@]}; do

      ./app $size 580 -p 0 -t gpu -d 0

  done

