#!/bin/bash
# change input dataset in array "dataset" and path "DATA..."
# change tesing count in var "seqcount"
# change number of iterations in "simtime"
# change number of thrs in array "thrsset_MC" "thrsset_D6" "thrsset_N8"
# store timing data in "RESULT"


# ----- dataset loop begin -----

dataset=(1024 2048 4096 8192)
#dataset=(32 64 128 256 512 1024)
#dataset=(8 16 32 64 128 256)

  for size in ${dataset[@]}; do

      ./padding $size

  done

