#!/bin/bash
# change input dataset in array "dataset" and path "DATA..."
# change tesing count in var "seqcount"
# change number of iterations in "simtime"
# change number of thrs in array "thrsset_MC" "thrsset_D6" "thrsset_N8"
# store timing data in "RESULT"


# ----- dataset loop begin -----

#dataset=(10240 20480 40960 81920 163840 327680)
dataset=(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16)
  for size in ${dataset[@]}; do

      ./image_convolution 2048 $size

  done

